### ISSUE TITLE
MIRZA output alignment shows incorrect matches and mismatches

### ISSUE THREAD

**Issue by sujaikumar** [guma44/MIRZAG#11]
Dear MIRZA/MIRZAG team

We use MIRZA to assign scores to miRNA/mRNA pairings. Somone just pointed out that the alignment matches and mismatches seem wrong.

I could be misunderstanding the output - so I'm going to paste the input files and output files here:

Input files:
[t.txt](https://github.com/zavolanlab/MIRZAG/files/3002938/t.txt)
[q.txt](https://github.com/zavolanlab/MIRZAG/files/3002939/q.txt)
[e.txt](https://github.com/zavolanlab/MIRZAG/files/3002940/e.txt)

Command:
```
MIRZA e.txt t.txt q.txt 55 noupdate >MIRZA.output.txt 2>/dev/null
```
[MIRZA.output.txt](https://github.com/zavolanlab/MIRZAG/files/3002951/MIRZA.output.txt)

If you look in this output file, the alignment section looks like this:
```
>ENSMUST00000175726.2   <<< VERSUS >>>  >mmu-let-7b-5p  ----> Ratio(H/Z0)= 0.67709
miRNA             5'    -------UGA---GGUAGUAGGUUGUGUGGU-------------------------- 3'    UGAGGUAGUAGGUUGUGUGGU
A L I G N M E N T       #######|||vvv||||OOOOO||||OO^^|##########################
mRNA   (reversed) 3'    CTAGAACATTGACCCATTGAAAAACACT--ATGTTAGATGAACAACACCAAATCAAC 5'    CTAGAACATTGACCCATTGAAAAACACTATGTTAGATGAACAACACCAAATCAAC
```

However, that seems wrong, because the second base of the miRNA is G, and the alignment string shows a match "I" with T in the reversed mRNA. Similarly there is a G aligned with a C towards the end, but that is marked as a mismatch with "O". I've highlighted these with an "*" below:

```
UGA---GGUAGUAGGUUGUGUGGU
|||vvv||||OOOOO||||OO^^|
ATTGACCCATTGAAAAACACT--A
 *                 *
```

Like I said, I could be misunderstanding the alignment format - so any insights you can provide on this would be much appreciated! Thanks as always for an otherwise very useful tool! :-)

**Comment by guma44** [comment]
Hi,
The G-T pair is just a G-U pair in the RNA (you have used  DNA string but this is "converted" to RNA). As far as G-C in the 3' end of the miRNA  is concerned, the possible explanation might be that this pairing was just unfavorable under the model considered. Mind that the base pairing is position dependent and some positions are less prone to pair than the other.

**Comment by sujaikumar** [comment]
Thanks for the prompt explainer... :-)
